name: task_tracker
description: Simple Task Track API.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  vaden: ^0.1.1
  uuid: ^4.4.2
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^0.1.2
